"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def fib(n): 
    """ all fib values upto n, n > 1
    """
    fibnums = [1,1]
    while sum(fibnums[-2:]) < n:
        next = fibnums
        fibnums.append(sum(fibnums[-2:]))
    return fibnums
    
def fib_even(n):
    """even fib values"""
    return filter(lambda x : x % 2 == 0, fib(n))
    
print sum(fib_even(4000000))